# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
   - name: autopy-lot
  uses: deep5050/autopy-lot@1.1
  with:
    # GITHUB_TOKEN secret < automatically provided by Github , you don't need to set up >
    github_token: 
    # Which files to check: all or just committed: all | latest
    check: # optional, default is all
    # File types to be converted : py | ipynb | r 
    input_type: # optional, default is ipynb
    # --opt comment_magics <see documentation> : false (default) | true 
    comment_magics: # optional, default is 
    # --opt split_at_heading <see documentation> :false (default) | true
    split_at_heading: # optional, default is 
    # Target output type: py | markdown | rmarkdown | r | ipynb
    output_type: # optional, default is py
    # Branch that the badge will target. Defaults to the current branch.
    target_branch: # optional, default is 
    # Branch that the badge will target on pull_request. Defaults to GITHUB_BASE_REF.
    pull_request_branch: # optional, default is 
    # Repository that the badge will target. Defaults to the current repository.
    target_repository: # optional, default is 
    # Repository that the badge will target on pull_request. Defaults to TARGET_REPOSITORY
    pull_request_repository: # optional, default is 
